# find all projects that have a license violation

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX maven: <http://maven.apache.org/artifact#>
PREFIX license: <http://maven.apache.org/license#>

SELECT DISTINCT ?projectVersion ?dependencyProjectVersion ?license

WHERE {
    
    GRAPH <urn:x-arq:UnionGraph>
    { 
        ?project rdf:type maven:Project .
        ?project maven:projectVersion ?projectVersion .
        ?projectVersion maven:depends ?dependency .
        ?dependency maven:dependency ?dependencyProjectVersion .
    }
    
    SERVICE <${sparqlEndpoint}>
    { 
        ?dependencyProjectVersion maven:license ?license .
        ?license license:permissive "no" .
    }

}
