# find all projects that have a vulnerability

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX maven: <http://maven.apache.org/artifact#>

SELECT DISTINCT ?projectVersion ?dependencyProjectVersion ?vulnerability

WHERE {
    
    GRAPH <urn:x-arq:UnionGraph>
    { 
        ?project rdf:type maven:Project .
        ?project maven:projectVersion ?projectVersion .
        ?projectVersion maven:depends ?dependency .
        ?dependency maven:dependency ?dependencyProjectVersion .
    }
    
    SERVICE <${sparqlEndpoint}>
    { 
        ?dependencyProjectVersion maven:vulnerability ?vulnerability .
    }

}
